In [1]:
import pandas as pd
import numpy as np #подключение библиотек

In [2]:
df = pd.read_csv('weatherAUS_clear.csv') #выгрузка данных в датасет
df

,Unnamed: 0,Date,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,0,2008-12-01,Albury,13.4,22.9,0.6,W,44.0,W,WNW,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,No,No
1,1,2008-12-02,Albury,7.4,25.1,0.0,WNW,44.0,NNW,WSW,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,No,No
2,2,2008-12-03,Albury,12.9,25.7,0.0,WSW,46.0,W,WSW,19.0,26.0,38.0,30.0,1007.6,1008.7,21.0,23.2,No,No
3,3,2008-12-04,Albury,9.2,28.0,0.0,NE,24.0,SE,E,11.0,9.0,45.0,16.0,1017.6,1012.8,18.1,26.5,No,No
4,4,2008-12-05,Albury,17.5,32.3,1.0,W,41.0,ENE,NW,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140782,145454,2017-06-20,Uluru,3.5,21.8,0.0,E,31.0,ESE,E,15.0,13.0,59.0,27.0,1024.7,1021.2,9.4,20.9,No,No
140783,145455,2017-06-21,Uluru,2.8,23.4,0.0,E,31.0,SE,ENE,13.0,11.0,51.0,24.0,1024.6,1020.3,10.1,22.4,No,No
140784,145456,2017-06-22,Uluru,3.6,25.3,0.0,NNW,22.0,SE,N,13.0,9.0,56.0,21.0,1023.5,1019.1,10.9,24.5,No,No
140785,145457,2017-06-23,Uluru,5.4,26.9,0.0,N,37.0,SE,WNW,9.0,9.0,53.0,24.0,1021.0,1016.8,12.5,26.1,No,No
140786,145458,2017-06-24,Uluru,7.8,27.0,0.0,SE,28.0,SSE,N,13.0,7.0,51.0,24.0,1019.4,1016.5,15.1,26.0,No,No

In [ ]:
df = df.drop(columns='Unnamed: 0')
df = df.drop(columns='Date')
df #удаление столбцов

In [3]:
from sklearn.preprocessing import OrdinalEncoder #подключение библиотеки

Oenc = OrdinalEncoder()
Oenc.fit(df[['Location','WindGustDir']]) #установка значения
df

,Unnamed: 0,Date,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,0,2008-12-01,Albury,13.4,22.9,0.6,W,44.0,W,WNW,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,No,No
1,1,2008-12-02,Albury,7.4,25.1,0.0,WNW,44.0,NNW,WSW,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,No,No
2,2,2008-12-03,Albury,12.9,25.7,0.0,WSW,46.0,W,WSW,19.0,26.0,38.0,30.0,1007.6,1008.7,21.0,23.2,No,No
3,3,2008-12-04,Albury,9.2,28.0,0.0,NE,24.0,SE,E,11.0,9.0,45.0,16.0,1017.6,1012.8,18.1,26.5,No,No
4,4,2008-12-05,Albury,17.5,32.3,1.0,W,41.0,ENE,NW,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140782,145454,2017-06-20,Uluru,3.5,21.8,0.0,E,31.0,ESE,E,15.0,13.0,59.0,27.0,1024.7,1021.2,9.4,20.9,No,No
140783,145455,2017-06-21,Uluru,2.8,23.4,0.0,E,31.0,SE,ENE,13.0,11.0,51.0,24.0,1024.6,1020.3,10.1,22.4,No,No
140784,145456,2017-06-22,Uluru,3.6,25.3,0.0,NNW,22.0,SE,N,13.0,9.0,56.0,21.0,1023.5,1019.1,10.9,24.5,No,No
140785,145457,2017-06-23,Uluru,5.4,26.9,0.0,N,37.0,SE,WNW,9.0,9.0,53.0,24.0,1021.0,1016.8,12.5,26.1,No,No
140786,145458,2017-06-24,Uluru,7.8,27.0,0.0,SE,28.0,SSE,N,13.0,7.0,51.0,24.0,1019.4,1016.5,15.1,26.0,No,No

In [4]:
Oenc.categories_ #ожидаемые категории

[array(['Adelaide', 'Albany', 'Albury', 'AliceSprings', 'BadgerysCreek',
        'Ballarat', 'Bendigo', 'Brisbane', 'Cairns', 'Canberra', 'Cobar',
        'CoffsHarbour', 'Dartmoor', 'Darwin', 'GoldCoast', 'Hobart',
        'Katherine', 'Launceston', 'Melbourne', 'MelbourneAirport',
        'Mildura', 'Moree', 'MountGambier', 'MountGinini', 'Newcastle',
        'Nhil', 'NorahHead', 'NorfolkIsland', 'Nuriootpa', 'PearceRAAF',
        'Penrith', 'Perth', 'PerthAirport', 'Portland', 'Richmond', 'Sale',
        'SalmonGums', 'Sydney', 'SydneyAirport', 'Townsville',
        'Tuggeranong', 'Uluru', 'WaggaWagga', 'Walpole', 'Watsonia',
        'Williamtown', 'Witchcliffe', 'Wollongong', 'Woomera'],
       dtype=object),
 array(['E', 'ENE', 'ESE', 'N', 'NE', 'NNE', 'NNW', 'NW', 'S', 'SE', 'SSE',
        'SSW', 'SW', 'Unknown', 'W', 'WNW', 'WSW'], dtype=object)]

In [5]:
Oenc = OrdinalEncoder()
df[['Location','WindGustDir']] = Oenc.fit_transform(df[['Location','WindGustDir']]) #установка значений и их преобразование
df

,Unnamed: 0,Date,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,0,2008-12-01,2.0,13.4,22.9,0.6,14.0,44.0,W,WNW,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,No,No
1,1,2008-12-02,2.0,7.4,25.1,0.0,15.0,44.0,NNW,WSW,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,No,No
2,2,2008-12-03,2.0,12.9,25.7,0.0,16.0,46.0,W,WSW,19.0,26.0,38.0,30.0,1007.6,1008.7,21.0,23.2,No,No
3,3,2008-12-04,2.0,9.2,28.0,0.0,4.0,24.0,SE,E,11.0,9.0,45.0,16.0,1017.6,1012.8,18.1,26.5,No,No
4,4,2008-12-05,2.0,17.5,32.3,1.0,14.0,41.0,ENE,NW,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140782,145454,2017-06-20,41.0,3.5,21.8,0.0,0.0,31.0,ESE,E,15.0,13.0,59.0,27.0,1024.7,1021.2,9.4,20.9,No,No
140783,145455,2017-06-21,41.0,2.8,23.4,0.0,0.0,31.0,SE,ENE,13.0,11.0,51.0,24.0,1024.6,1020.3,10.1,22.4,No,No
140784,145456,2017-06-22,41.0,3.6,25.3,0.0,6.0,22.0,SE,N,13.0,9.0,56.0,21.0,1023.5,1019.1,10.9,24.5,No,No
140785,145457,2017-06-23,41.0,5.4,26.9,0.0,3.0,37.0,SE,WNW,9.0,9.0,53.0,24.0,1021.0,1016.8,12.5,26.1,No,No
140786,145458,2017-06-24,41.0,7.8,27.0,0.0,9.0,28.0,SSE,N,13.0,7.0,51.0,24.0,1019.4,1016.5,15.1,26.0,No,No

In [6]:
from sklearn.preprocessing import LabelEncoder #подключение библиотеки
Lenc = LabelEncoder()
Lenc.fit(df['RainTomorrow']) #установка кодировщика меток
df['RainTomorrow'] = Lenc.fit_transform(df['RainTomorrow']) #возврат закодированных меток
df

,Unnamed: 0,Date,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,0,2008-12-01,2.0,13.4,22.9,0.6,14.0,44.0,W,WNW,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,No,0
1,1,2008-12-02,2.0,7.4,25.1,0.0,15.0,44.0,NNW,WSW,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,No,0
2,2,2008-12-03,2.0,12.9,25.7,0.0,16.0,46.0,W,WSW,19.0,26.0,38.0,30.0,1007.6,1008.7,21.0,23.2,No,0
3,3,2008-12-04,2.0,9.2,28.0,0.0,4.0,24.0,SE,E,11.0,9.0,45.0,16.0,1017.6,1012.8,18.1,26.5,No,0
4,4,2008-12-05,2.0,17.5,32.3,1.0,14.0,41.0,ENE,NW,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140782,145454,2017-06-20,41.0,3.5,21.8,0.0,0.0,31.0,ESE,E,15.0,13.0,59.0,27.0,1024.7,1021.2,9.4,20.9,No,0
140783,145455,2017-06-21,41.0,2.8,23.4,0.0,0.0,31.0,SE,ENE,13.0,11.0,51.0,24.0,1024.6,1020.3,10.1,22.4,No,0
140784,145456,2017-06-22,41.0,3.6,25.3,0.0,6.0,22.0,SE,N,13.0,9.0,56.0,21.0,1023.5,1019.1,10.9,24.5,No,0
140785,145457,2017-06-23,41.0,5.4,26.9,0.0,3.0,37.0,SE,WNW,9.0,9.0,53.0,24.0,1021.0,1016.8,12.5,26.1,No,0
140786,145458,2017-06-24,41.0,7.8,27.0,0.0,9.0,28.0,SSE,N,13.0,7.0,51.0,24.0,1019.4,1016.5,15.1,26.0,No,0

In [7]:
Lenc.classes_ #метки для всех классов

array(['No', 'Yes'], dtype=object)

In [8]:
from sklearn.preprocessing import OneHotEncoder #подключение библиотеки
Onhot = OneHotEncoder()
Onhot.fit_transform(df[['RainToday']]).toarray() #совоставление данных и преобразование в массив

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [9]:
df[['RainToday', 'RainTodayYes']] = Onhot.fit_transform(df[['RainToday']]).toarray() #совоставление данных и преобразование в массив по столбцам
df

,Unnamed: 0,Date,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RainTomorrow,RainTodayYes
0,0,2008-12-01,2.0,13.4,22.9,0.6,14.0,44.0,W,WNW,...,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,1.0,0,0.0
1,1,2008-12-02,2.0,7.4,25.1,0.0,15.0,44.0,NNW,WSW,...,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,1.0,0,0.0
2,2,2008-12-03,2.0,12.9,25.7,0.0,16.0,46.0,W,WSW,...,26.0,38.0,30.0,1007.6,1008.7,21.0,23.2,1.0,0,0.0
3,3,2008-12-04,2.0,9.2,28.0,0.0,4.0,24.0,SE,E,...,9.0,45.0,16.0,1017.6,1012.8,18.1,26.5,1.0,0,0.0
4,4,2008-12-05,2.0,17.5,32.3,1.0,14.0,41.0,ENE,NW,...,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,1.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140782,145454,2017-06-20,41.0,3.5,21.8,0.0,0.0,31.0,ESE,E,...,13.0,59.0,27.0,1024.7,1021.2,9.4,20.9,1.0,0,0.0
140783,145455,2017-06-21,41.0,2.8,23.4,0.0,0.0,31.0,SE,ENE,...,11.0,51.0,24.0,1024.6,1020.3,10.1,22.4,1.0,0,0.0
140784,145456,2017-06-22,41.0,3.6,25.3,0.0,6.0,22.0,SE,N,...,9.0,56.0,21.0,1023.5,1019.1,10.9,24.5,1.0,0,0.0
140785,145457,2017-06-23,41.0,5.4,26.9,0.0,3.0,37.0,SE,WNW,...,9.0,53.0,24.0,1021.0,1016.8,12.5,26.1,1.0,0,0.0
140786,145458,2017-06-24,41.0,7.8,27.0,0.0,9.0,28.0,SSE,N,...,7.0,51.0,24.0,1019.4,1016.5,15.1,26.0,1.0,0,0.0

In [10]:
df = df.drop(columns='RainToday') #удаление столбца
df

,Unnamed: 0,Date,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainTomorrow,RainTodayYes
0,0,2008-12-01,2.0,13.4,22.9,0.6,14.0,44.0,W,WNW,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,0,0.0
1,1,2008-12-02,2.0,7.4,25.1,0.0,15.0,44.0,NNW,WSW,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,0,0.0
2,2,2008-12-03,2.0,12.9,25.7,0.0,16.0,46.0,W,WSW,19.0,26.0,38.0,30.0,1007.6,1008.7,21.0,23.2,0,0.0
3,3,2008-12-04,2.0,9.2,28.0,0.0,4.0,24.0,SE,E,11.0,9.0,45.0,16.0,1017.6,1012.8,18.1,26.5,0,0.0
4,4,2008-12-05,2.0,17.5,32.3,1.0,14.0,41.0,ENE,NW,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140782,145454,2017-06-20,41.0,3.5,21.8,0.0,0.0,31.0,ESE,E,15.0,13.0,59.0,27.0,1024.7,1021.2,9.4,20.9,0,0.0
140783,145455,2017-06-21,41.0,2.8,23.4,0.0,0.0,31.0,SE,ENE,13.0,11.0,51.0,24.0,1024.6,1020.3,10.1,22.4,0,0.0
140784,145456,2017-06-22,41.0,3.6,25.3,0.0,6.0,22.0,SE,N,13.0,9.0,56.0,21.0,1023.5,1019.1,10.9,24.5,0,0.0
140785,145457,2017-06-23,41.0,5.4,26.9,0.0,3.0,37.0,SE,WNW,9.0,9.0,53.0,24.0,1021.0,1016.8,12.5,26.1,0,0.0
140786,145458,2017-06-24,41.0,7.8,27.0,0.0,9.0,28.0,SSE,N,13.0,7.0,51.0,24.0,1019.4,1016.5,15.1,26.0,0,0.0

In [11]:
from sklearn.preprocessing import Normalizer #импорт библиотеки

Norm = Normalizer()

df[['Pressure9am', 'Pressure3pm']] = Norm.fit_transform(df[['Pressure9am', 'Pressure3pm']]) #преобразование данных числовых столбцов
df

,Unnamed: 0,Date,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainTomorrow,RainTodayYes
0,0,2008-12-01,2.0,13.4,22.9,0.6,14.0,44.0,W,WNW,20.0,24.0,71.0,22.0,0.707317,0.706896,16.9,21.8,0,0.0
1,1,2008-12-02,2.0,7.4,25.1,0.0,15.0,44.0,NNW,WSW,4.0,22.0,44.0,25.0,0.708087,0.706125,17.2,24.3,0,0.0
2,2,2008-12-03,2.0,12.9,25.7,0.0,16.0,46.0,W,WSW,19.0,26.0,38.0,30.0,0.706721,0.707492,21.0,23.2,0,0.0
3,3,2008-12-04,2.0,9.2,28.0,0.0,4.0,24.0,SE,E,11.0,9.0,45.0,16.0,0.708776,0.705433,18.1,26.5,0,0.0
4,4,2008-12-05,2.0,17.5,32.3,1.0,14.0,41.0,ENE,NW,7.0,20.0,82.0,33.0,0.708788,0.705422,17.8,29.7,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140782,145454,2017-06-20,41.0,3.5,21.8,0.0,0.0,31.0,ESE,E,15.0,13.0,59.0,27.0,0.708315,0.705896,9.4,20.9,0,0.0
140783,145455,2017-06-21,41.0,2.8,23.4,0.0,0.0,31.0,SE,ENE,13.0,11.0,51.0,24.0,0.708592,0.705618,10.1,22.4,0,0.0
140784,145456,2017-06-22,41.0,3.6,25.3,0.0,6.0,22.0,SE,N,13.0,9.0,56.0,21.0,0.708628,0.705582,10.9,24.5,0,0.0
140785,145457,2017-06-23,41.0,5.4,26.9,0.0,3.0,37.0,SE,WNW,9.0,9.0,53.0,24.0,0.708563,0.705648,12.5,26.1,0,0.0
140786,145458,2017-06-24,41.0,7.8,27.0,0.0,9.0,28.0,SSE,N,13.0,7.0,51.0,24.0,0.708113,0.706099,15.1,26.0,0,0.0

In [13]:
from sklearn.model_selection import train_test_split #импорт библиотеки для разбития на подмножества

Y = df['RainTomorrow'] #присвоение х и у
X = df.drop(columns=['RainTomorrow'])

x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.2, random_state=42) 
#формирование разделённых данных с размером текста и перетасовкой данных int

In [14]:
x_train #вызовы разделённых данных

,Unnamed: 0,Date,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainTodayYes
119008,123230,2015-11-03,31.0,13.5,26.0,0.0,12.0,33.0,ENE,SW,7.0,17.0,52.0,48.0,0.707975,0.706238,21.4,24.8,0.0
68281,71385,2011-10-20,20.0,16.0,30.0,0.0,3.0,43.0,N,N,31.0,11.0,24.0,22.0,0.707695,0.706518,25.6,29.8,0.0
42953,44749,2015-03-11,47.0,19.0,26.3,0.0,4.0,41.0,NNW,NNE,7.0,15.0,85.0,79.0,0.708429,0.705782,21.8,24.4,0.0
91339,94829,2013-05-27,39.0,14.7,27.2,0.0,0.0,50.0,SSW,E,13.0,22.0,48.0,47.0,0.707904,0.706309,21.7,25.8,0.0
26428,27344,2009-06-27,34.0,5.7,15.5,0.0,2.0,11.0,Unknown,WSW,0.0,6.0,99.0,63.0,0.708230,0.705982,8.8,15.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110268,114114,2016-02-06,46.0,15.4,24.8,0.0,10.0,48.0,SSE,SSE,26.0,30.0,68.0,58.0,0.707454,0.706759,21.2,22.2,0.0
119879,124103,2009-09-30,36.0,3.2,15.5,9.2,11.0,43.0,SSW,SSW,15.0,26.0,72.0,75.0,0.707940,0.706273,12.1,11.6,1.0
103694,107412,2014-04-24,48.0,11.7,23.6,0.0,9.0,37.0,S,SE,22.0,22.0,71.0,34.0,0.708287,0.705924,15.6,23.4,0.0
131932,136480,2010-01-14,3.0,20.2,34.5,0.0,9.0,37.0,ESE,ESE,26.0,17.0,44.0,24.0,0.708260,0.705952,26.2,33.6,0.0
121958,126230,2015-11-02,36.0,11.9,23.0,3.8,11.0,50.0,E,SSW,9.0,26.0,84.0,68.0,0.707940,0.706273,17.0,19.7,1.0

In [15]:
x_test

,Unnamed: 0,Date,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainTodayYes
117237,121459,2010-09-30,31.0,18.2,25.0,0.0,9.0,33.00000,SE,SE,9.0,9.0,41.0,34.0,0.707631,0.706582,19.2,24.4,0.0
31026,32051,2013-06-18,37.0,8.0,19.2,0.0,8.0,43.00000,W,S,26.0,17.0,76.0,52.0,0.707560,0.706653,9.6,16.1,0.0
103982,107700,2015-02-06,48.0,19.1,38.5,0.0,1.0,52.00000,ESE,NNE,19.0,22.0,21.0,9.0,0.708046,0.706167,25.2,37.0,0.0
25635,26526,2015-09-24,30.0,8.4,17.5,0.0,8.0,54.00000,SSW,S,22.0,26.0,47.0,44.0,0.707940,0.706273,13.5,15.4,0.0
105836,109566,2011-09-22,1.0,9.5,14.5,2.4,13.0,39.97052,SW,SSW,19.0,9.0,58.0,53.0,0.706865,0.707349,12.2,13.8,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16440,17003,2014-06-09,24.0,7.0,19.4,0.2,13.0,39.97052,Unknown,SW,0.0,19.0,76.0,75.0,0.707940,0.706273,11.8,16.4,0.0
87608,90988,2010-12-19,14.0,21.0,23.4,2.2,10.0,37.00000,SW,SSE,9.0,24.0,76.0,91.0,0.707563,0.706650,21.9,18.8,1.0
37237,38277,2014-01-12,42.0,18.8,39.0,0.0,15.0,46.00000,E,SSE,13.0,13.0,38.0,12.0,0.708256,0.705955,27.4,37.4,0.0
96573,100247,2010-12-05,22.0,15.7,32.8,0.0,9.0,52.00000,ENE,NNE,19.0,13.0,65.0,34.0,0.708227,0.705985,23.5,32.7,0.0
8179,8369,2015-08-07,10.0,3.4,14.7,0.4,11.0,26.00000,S,SW,9.0,11.0,73.0,46.0,0.708140,0.706072,8.1,14.3,0.0

In [16]:
y_train

119008    0
68281     0
42953     0
91339     0
26428     0
         ..
110268    0
119879    1
103694    0
131932    0
121958    1
Name: RainTomorrow, Length: 112629, dtype: int32

In [17]:
y_test

117237    0
31026     1
103982    0
25635     0
105836    0
         ..
16440     1
87608     1
37237     0
96573     1
8179      0
Name: RainTomorrow, Length: 28158, dtype: int32

In [18]:
print('Количестов входных обучающих данных', len(x_train)) #вывод размеров массивов разделённых по типам данных
print('Количестов проверочных обучающих данных', len(y_train))
print('Количестов входных тестовых данных', len(x_test))
print('Количестов проверочных тестовых данных', len(y_test))

Количестов входных обучающих данных 112629
Количестов проверочных обучающих данных 112629
Количестов входных тестовых данных 28158
Количестов проверочных тестовых данных 28158